/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulbra.br.view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.saolucas
 */
public class ProjetoFinal extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoFinal
     */
    public ProjetoFinal() {
        initComponents();
        gerarAnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup6 = new javax.swing.ButtonGroup();
        checkbox1 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        lbDia = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        cboxMes = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        cbAnos = new javax.swing.JComboBox<>();
        lbDescubra = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 172, 137));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNome.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome completo:");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, 30));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 430, 30));

        lbSexo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo:");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lbDia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbDia.setForeground(new java.awt.Color(255, 255, 255));
        lbDia.setText("Dia:");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 30));

        lbMes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setText("Mês:");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 70, 30));

        lbAno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbAno.setForeground(new java.awt.Color(255, 255, 255));
        lbAno.setText("Ano:");
        jPanel1.add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 70, 30));

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 120, 40));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 120, 40));

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Novembro", "Dezembro" }));
        cboxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMesActionPerformed(evt);
            }
        });
        jPanel1.add(cboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 40));

        cbDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiaActionPerformed(evt);
            }
        });
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 40));

        cbAnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnosActionPerformed(evt);
            }
        });
        jPanel1.add(cbAnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 40));

        lbDescubra.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbDescubra.setForeground(new java.awt.Color(255, 255, 255));
        lbDescubra.setText("Descubra seu signo");
        jPanel1.add(lbDescubra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 550, 80));

        lbData.setBackground(new java.awt.Color(255, 255, 255));
        lbData.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setText("Data de nascimento");
        jPanel1.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 290, 30));

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/zo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 1150, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed


    }//GEN-LAST:event_txtNomeActionPerformed

    public static void calcularIdade(int dia, int mes, int ano){
        
     
       
               
    }
    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        String nome = txtNome.getText();
        nome = nome.replaceAll(" ", "");
        int tamanho = nome.length();
        if (tamanho < 8) {
            JOptionPane.showMessageDialog(this, "Bonito o nome, pena que ele não é verdadeiro");

        }
        
        
    }//GEN-LAST:event_btConsultarActionPerformed
    public void gerarAnos() {
        ArrayList anos = new ArrayList();
        int ano = 1900;
        for (int i = 0; i <= 124; i++) {
            anos.add(ano);
            ano++;
        }
        DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(anos.toArray());
        cbAnos.setModel(defaultComboBox);

    }
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void cboxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxMesActionPerformed

    private void cbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiaActionPerformed

    private void cbAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnosActionPerformed

    }//GEN-LAST:event_cbAnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbAnos;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cboxMes;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDescubra;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
